name: Release-plz
# see https://marcoieni.github.io/release-plz/github/index.html#example-release-pr-and-release
# for more information

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Rust toolchain (stable)
        uses: dtolnay/rust-toolchain@stable
      - name: Run release-plz
        uses: joshka/release-plz-action@c39e7f1959e30f3d0178027328895055a74aa955
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
